# Generated by Django 4.2.26 on 2025-11-24 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('cve_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vulnerability')),
            ],
            options={
                'verbose_name_plural': 'Watchlist Items',
                'unique_together': {('user', 'vulnerability')},
            },
        ),
    ]
